apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: fib-go
  namespace: graphtuitous
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: fib-go
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: fib-go-
      labels:
        build.appstudio.openshift.io/application: graphtuitous
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: fib-go
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: graphtuitous
    spec:
      params:
      - name: git-url
        value: https://github.com/jduimovich/graphtuitous
      - name: output-image
        value: quay.io/jduimovich0/fib-go:latest-$(tt.params.git-revision)
      - name: dockerfile
        value: services/fib-go/Dockerfile
      - name: path-context
        value: services/fib-go
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle:ad4c34b71d468a991450b0091cd96765471ed82d
        name: docker-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: fib-go/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
